CREATE DOMAIN AGE AS INTEGER CHECK (VALUE > 0 AND VALUE < 150);

DROP TABLE IF EXISTS AUTHORS;

CREATE TABLE AUTHORS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  FirstName VARCHAR(250) NOT NULL,
  LastName VARCHAR(250) NOT NULL,
  Age AGE
);

DROP TABLE IF EXISTS GENRES;

CREATE TABLE GENRES (
  id INT AUTO_INCREMENT PRIMARY KEY,
  Title VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS BOOKS;

CREATE TABLE BOOKS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  Title VARCHAR(250) NOT NULL,
  Recommended_price INT NOT NULL,
  Authors_id INT NOT NULL,
  Genres_id INT NOT NULL,
  FOREIGN KEY (Genres_id) REFERENCES GENRES (id),
  FOREIGN KEY (Authors_id) REFERENCES AUTHORS (id)
);

CREATE INDEX INDEX_PRICE ON BOOKS(Recommended_price);

